version: 2.1

# Enable CircleCI's dynamic configuration feature
setup: true

# Enable path-based pipeline
orbs:
  path-filtering: circleci/path-filtering@0.1.0

workflows:
  Generate dynamic configuration:
    jobs:
      - path-filtering/filter:
          name: Check updated files
          config-path: .circleci/continue.yml
          base-revision: master
          mapping: |
            terraform/.* terraform-job true


